### ISSUE TITLE
Car losing brakes

### ISSUE THREAD

**Issue by maguhd** [Qbox-project/qbx_vehiclefailure#4] opened 2023-09-01 10:01 UTC
### Summary

Car losing brakes

### Reproduction

1. Enter a car.
2. Drive around.
3. Exit car.
4. Enter car.
5. Drive.
6. F8 - https://i.imgur.com/4UEG9Gu.png
7. No brakes.

### Expected behavior

Having brakes.

### Actual behavior

No brakes.

### Last Updated

Today

### Custom Resources

No

### Resource Rename

I didnt rename the resource.

**Comment by mockdot** [comment] 2023-09-01 16:34
Was able to reproduce, as well as some other players in my server, it looks like there's a problem that after entering the vehicle it no longer finds the vehicle handling?

[  10295266] [b2802_GTAProce]             MainThrd/ no entity for vehicle 0 in GET_VEHICLE_HANDLING_FLOAT
[  10295266] [b2802_GTAProce]             MainThrd/ no script guid for vehicle 0 in SET_VEHICLE_HANDLING_FIELD

So this happens right exactly after EXITING the vehicle. I am guessing something is modifying the handling on exit

**Comment by mockdot** [comment] 2023-09-01 17:00
#5

**Comment by maguhd** [comment] 2023-09-02 07:51
Life saver. Can't believe I didnt think of that. Thank you!

**Comment by maguhd** [comment] 2023-09-02 08:02
Looks like it does not happen in cars anymore. I tried a helicopter and still got the error.
https://i.imgur.com/nqPOyY6.png

Edit: Can't reproduce anymore. Looks like it was a 1 time thing. But happened.

**Comment by mockdot** [comment] 2023-09-09 16:07
That is probably due to the way the script spawns the vehicle, but it seems like the issue is now fixed. Closing this.

**Closed as completed by mockdot** 2023-09-09 16:07 UTC
Labels: bug, need repro
